import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ChevronRight, FileCode } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { dataService } from '../services/dataService';
import { useLiveData } from '../context/LiveDataContext';
import { formatDateTime } from '../utils/format';
import { Harvest } from '../types';

export const HarvestsView: React.FC = () => {
 const { version } = useLiveData();
 const [harvests, setHarvests] = useState<Harvest[]>([]);

 const loadHarvests = () => {
 setHarvests(dataService.getHarvests());
 };

 useEffect(() => {
 loadHarvests();
 }, [version]);

 return (
 <div className="max-w-6xl mx-auto py-6 px-4 space-y-6">
 <PageHeader
 title="Artifact Harvests"
 subtitle="Source extractions, Markdown findings, and candidates generated by LLM analysis"
 ttsContent="Artifact harvests overview."
 />

 <div className="space-y-4">
 {harvests.map((h) => (
 <div key={h.id} className="app-panel p-4 space-y-3">
 <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-3">
 <div className="flex items-center gap-3">
 <FileCode className="w-5 h-5 text-emerald-600 " />
 <div>
 <h2 className="text-sm font-bold text-slate-900 font-mono"><Link to={`/harvests/${h.id}`} className="hover:text-indigo-600 :text-indigo-400 transition-colors">{h.sourceFilename || h.id}</Link></h2>
 <p className="text-[11px] text-slate-400 font-mono">Model: {h.model || 'Unknown'}</p>
 </div>
 </div>
 <div className="flex items-center gap-3 text-sm font-mono text-slate-500 ">
 <span>{h.totalCandidates || 0} candidates</span>
 <span>{h.fileSize || 0} bytes</span>
 <span>{formatDateTime(h.createdAt)}</span>
 </div>
 </div>

 <div className="bg-slate-50 p-3 border border-slate-200 font-mono text-sm text-slate-700 whitespace-pre-line">
 {h.sourceText}
 </div>

 <div className="pt-2 flex justify-end">
 <Link
 to={`/harvests/${h.id}`}
 className="inline-flex items-center gap-1 text-indigo-400 hover:underline text-sm font-medium"
 >
 <span>Full Harvest Details</span>
 <ChevronRight className="w-3.5 h-3.5" />
 </Link>
 </div>
 </div>
 ))}
 </div>
 </div>
 );
};
