import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Sprout, Edit3, Save, ChevronRight, FileCode } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { dataService } from '../services/dataService';
import { useToast } from '../context/ToastContext';
import { Harvest } from '../types';

export const HarvestsView: React.FC = () => {
  const [harvests, setHarvests] = useState<Harvest[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editText, setEditText] = useState('');
  const { showToast } = useToast();

  const loadHarvests = () => {
    setHarvests(dataService.getHarvests());
  };

  useEffect(() => {
    loadHarvests();
  }, []);

  const handleStartEdit = (h: Harvest) => {
    setEditingId(h.id);
    setEditText(h.sourceText || '');
  };

  const handleSaveEdit = (id: string) => {
    dataService.updateHarvest(id, editText);
    setEditingId(null);
    showToast('Harvest source text updated!', 'success');
    loadHarvests();
  };

  return (
    <div className="max-w-6xl mx-auto py-6 px-4 space-y-6">
      <PageHeader
        title="Artifact Harvests"
        subtitle="Source extractions, Markdown findings, and candidates generated by LLM analysis"
        ttsContent="Artifact harvests overview."
      />

      <div className="space-y-4">
        {harvests.map((h) => (
          <div key={h.id} className="bg-slate-800/60 border border-slate-700/80 rounded-xl p-5 space-y-3 shadow-sm">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700/50 pb-3">
              <div className="flex items-center gap-3">
                <FileCode className="w-5 h-5 text-emerald-400" />
                <div>
                  <h2 className="text-sm font-bold text-white font-mono">{h.sourceFilename || h.id}</h2>
                  <p className="text-[11px] text-slate-400 font-mono">Model: {h.model || 'Unknown'}</p>
                </div>
              </div>
              <div className="flex items-center gap-3 text-xs font-mono text-slate-400">
                <span>{h.totalCandidates || 0} candidates</span>
                <span>{h.fileSize || 0} bytes</span>
              </div>
            </div>

            {editingId === h.id ? (
              <div className="space-y-2">
                <textarea
                  rows={5}
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  className="w-full bg-slate-900 font-mono text-xs p-3 text-indigo-300 border border-slate-700 rounded-lg focus:outline-none focus:border-indigo-500"
                />
                <div className="flex justify-end gap-2">
                  <button
                    onClick={() => setEditingId(null)}
                    className="px-3 py-1 text-xs text-slate-400 hover:text-white"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={() => handleSaveEdit(h.id)}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium rounded-lg shadow-sm"
                  >
                    <Save className="w-3.5 h-3.5" />
                    <span>Save Text</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="relative group bg-slate-900/50 p-3 rounded-lg border border-slate-700/50 font-mono text-xs text-slate-300 whitespace-pre-line">
                {h.sourceText}
                <button
                  onClick={() => handleStartEdit(h)}
                  className="absolute top-2 right-2 p-1.5 bg-slate-800 border border-slate-700 rounded-md text-slate-400 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity"
                  title="Edit Source Text"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                </button>
              </div>
            )}

            <div className="pt-2 flex justify-end">
              <Link
                to={`/harvests/${h.id}`}
                className="inline-flex items-center gap-1 text-indigo-400 hover:underline text-xs font-medium"
              >
                <span>Full Harvest Details</span>
                <ChevronRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
